#!/usr/bin/env python
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.by import By
from colorama import init, Fore, Back, Style
import argparse, importlib, traceback

def check_route_ready(browser):
    return browser.execute_script('return window.Router.route_ready;')

def wait_for_router_ready(browser):
    WebDriverWait(browser, 5).until(check_route_ready)

def show_success(test, browser):
    print(Fore.GREEN+Style.BRIGHT+'SUCCESS :'+Style.RESET_ALL+' %s  in %s !\n' %(test['name'], browser.name))

def show_failure(test, browser, debuginf):
    print(Fore.WHITE+Back.RED+Style.BRIGHT+'FAILURE :'+Style.RESET_ALL+' %s  in %s !\n' %(test['name'], browser.name))
    print(debuginf)



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Front-end UI tester\n\nUsage: uitester --chrome --firefox testfile')
    parser.add_argument('--chrome', action='store_true')
    parser.add_argument('--firefox', action='store_true')
    parser.add_argument('testfile', action='store', help='Test serie (python file in folder tests)')
    ARGS = parser.parse_args()


    browsers=[]

    ts = importlib.import_module('tests.%s' %ARGS.testfile)

    if ARGS.chrome:        
        browsers.append(webdriver.Chrome())

    if ARGS.firefox:
        browsers.append(webdriver.Firefox())


    for browser in browsers:
        for test in ts.test_serie:
            try:
                browser.get(test['url'])
                wait_for_router_ready(browser)
                if callable(test['check']):
                    if test['check'](browser):
                        show_success(test, browser)
                    else:
                        show_failure(test, browser, test['debuginfo'](browser))
            except Exception as e:
                print('\n======> ERROR in your test file (%s)  <======\n\n %s' %(ARGS.testfile,traceback.format_exc()))

        browser.close()

## https://www.guru99.com/execute-javascript-selenium-webdriver.html        