baseurl = 'https://eismea.internike.com'
test_serie = [
    {   'name'      : 'Trying non-existing route to defaultRoute',
        'url'       : baseurl + '/doesnotexist',
        'do'        : [ ],
        'check'     : lambda browser: 'Doh, this app does not serve this URL !' in browser.find_element_by_css_selector('body').text,
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },
    {   'name'      : 'Trying that "/" is routed to "defaultRoute.modulesChoice"',
        'url'       : baseurl + '',
        'do'        : [ ],
        'check'     : lambda browser: 'Choose your module' in browser.find_element_by_css_selector('body').text,
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },    
    {   'name'      : 'Trying that "/app1" is routed app1.app1MainCtrl, method forced to "home" by config',
        'url'       : baseurl + '/app1',
        'do'        : [ ],
        'check'     : lambda browser: 'Called home' in browser.find_element_by_css_selector('body').text,
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },
    {   'name'      : 'Trying that "/app1/helloWorld" is routed app1.app1MainCtrl, method "helloWorld" taken from URL',
        'url'       : baseurl + '/app1/helloWorld',
        'do'        : [ ],
        'check'     : lambda browser: 'Called helloWorld' in browser.find_element_by_css_selector('body').text,
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },
    {   'name'      : 'Trying that "/app1/badmethod" is routed to defaultRoute, with "Could not find method" error',
        'url'       : baseurl + '/app1/badmethod',
        'do'        : [ ],
        'check'     : lambda browser: ('Doh, this app does not serve this URL !' in browser.find_element_by_css_selector('body').text) 
                                  and ('Error: Could not find method' in browser.find_element_by_css_selector('body').text),
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },          
    {   'name'      : 'Trying that "/app1/user/123" is routed to UserCtrl, method "userDetails", params uid=123',
        'url'       : baseurl + '/app1/user/123',
        'do'        : [ ],
        'check'     : lambda browser: ('Called userDetails' in browser.find_element_by_css_selector('body').text) 
                                  and ( '"uid":"123' in browser.find_element_by_css_selector('body').text),
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    }, 
    {   'name'      : 'Trying that "/app1/user/123" is routed to a non-existing controller, and falls back to 404',
        'url'       : baseurl + '/app1/user/123',
        'do'        : [ ],
        'check'     : lambda browser: ('Called userDetails' in browser.find_element_by_css_selector('body').text) 
                                  and ( '"uid":"132' in browser.find_element_by_css_selector('body').text),
        'debuginfo' : lambda browser: 'Content: %s\n' %browser.find_element_by_css_selector('body').text,
    },     
]    
